import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <script dangerouslySetInnerHTML={{ __html: `
          (function() {
            var h = new Date().toLocaleTimeString("en-US", { timeZone: "America/New_York", hour: "numeric", hour12: false });
            var hr = parseInt(h);
            var bg = "", color = "";
            if (hr >= 22 || hr < 4) { bg = "#020617"; color = "white"; }
            else if (hr >= 17) { bg = "#BE123C"; color = "white"; }
            else if (hr >= 4 && hr < 8) { bg = "#431407"; color = "white"; }
            if (bg) { document.body.style.backgroundColor = bg; document.body.style.color = color; }
          })();
        `}} />
        {children}
      </body>
    </html>
  );
}
